#!/bin/bash
# /etc/init.d/YHHB

# ******************************************
#               YHHB v0.1.0
#                       By YinHang
#      https://github.com/YinHangCode/YHHB
#                      QQ Group: 107927710
# ******************************************

version="0.1.0"
basepath=$(cd `dirname $0`; pwd);

# config ###########################################

# 指定启动用户 空为不指定
#STARTUP_USER="pi"
STARTUP_USER=""


# 日志文件打印路径
# "${basepath}/logs/" 为脚本所在目录下logs文件
# "/home/pi/YHHB_logs/" 为记录日志到/home/pi/YHHB_logs/目录下
# "" 为不保存
LOG_FILE_PATH="${basepath}/logs/"
#LOG_FILE_PATH="/home/pi/YHHB_logs/"
#LOG_FILE_PATH=""


# 插件目录 不移动插件指明插件所在路径 移动插件设备空
PLUGIN_FILE_PATH=""
#PLUGIN_FILE_PATH="/usr/local/lib/node_modules/"


# 多HomeBridge位置 
# 目录结构例：
# '/home/pi/YHHB/hbs/MiAqaraPlatform/' 配置在该位置的路径
#   '/home/pi/YHHB/hbs/MiAqaraPlatform/config' HomeBridge配置文件路径
#   '/home/pi/YHHB/hbs/MiAqaraPlatform/plugin' HomeBridge插件文件路径 PLUGIN_FILE_PATH为空时有效
# '/home/pi/YHHB/hbs/MiPhilipsLightPlatform/' 配置在该位置的路径
#   '/home/pi/YHHB/hbs/MiPhilipsLightPlatform/config' HomeBridge配置文件路径
#   '/home/pi/YHHB/hbs/MiPhilipsLightPlatform/plugin' HomeBridge插件文件路径 PLUGIN_FILE_PATH为空时有效
hbPaths=(
'/home/pi/YHHB/hbs/BroadlinkRM/'
'/home/pi/YHHB/hbs/YeeLight/'
'/home/pi/YHHB/hbs/MiAqaraPlatform/'
'/home/pi/YHHB/hbs/RaspberryPi/'
'/home/pi/YHHB/hbs/Others/'
'/home/pi/YHHB/hbs/MiOutletPlatform/'
'/home/pi/YHHB/hbs/MiRobotVacuumPlatform/'
'/home/pi/YHHB/hbs/IkonkeOutletPlatform/'
'/home/pi/YHHB/hbs/IkonkeLightPlatform/'
'/home/pi/YHHB/hbs/MiPhilipsLightPlatform/'
'/home/pi/YHHB/hbs/MiFanPlatform/'
);

####################################################

if [ -n "$LOG_FILE_PATH" ]; then
    mkdir "$LOG_FILE_PATH"
    echo "[WARN] mkdir $LOG_FILE_PATH"
fi

getRunningNum() {
    runningNum=0;
    for hbPath in ${hbPaths[@]}; do
        pid=`ps -ef | grep homebridge | grep $hbPath | grep -v grep | awk '{print $2}'`
        if [ -n "$pid" ]; then
            runningNum=$(($runningNum+1))
        fi
    done
    return $runningNum;
}

status() {
    for hbPath in ${hbPaths[@]}; do
        pid=`ps -ef | grep homebridge | grep $hbPath | grep -v grep | awk '{print $2}'`
        if [ -z "$pid" ]; then
            echo -n "[Not Run]"
        else
            echo -n "[Running]"
        fi
        echo -n " "
        echo -n $pid
        echo -n -e "\t"
        echo -n $hbPath
        echo ""
    done
}

toggle() {
    getRunningNum;
    runningNum=$?
    if [ $runningNum -ne 0 ]; then
        stop;
    else
        start;
    fi
}

start() {
    getRunningNum;
    runningNum=$?
    if [ $runningNum -ne 0 ]; then
        echo "[WARN] YHHB is runing.";
    else
        for hbPath in ${hbPaths[@]}; do
            cmd="";
            if [ -n "$STARTUP_USER" ]; then
                cmd="$cmd""sudo -i -u $STARTUP_USER ";
            fi
            cmd="$cmd""nohup ";
            cmd="$cmd""./homebridge -U $hbPath/config/ ";
            if [ -n "$PLUGIN_FILE_PATH" ]; then
                cmd="$cmd""-P $PLUGIN_FILE_PATH";
            else
                cmd="$cmd""-P $hbPath/plugin/";
            fi
            cmd="$cmd"" >> ";
            if [ -n "$LOG_FILE_PATH" ]; then
                cmd="$cmd""$LOG_FILE_PATH/$(basename $hbPath).log";
            else
                cmd="$cmd""/dev/null";
            fi
            cmd="$cmd"" 2>&1 &";
            
            # echo "$cmd"
            eval "$cmd"
        done
    fi
}

stop() {
    getRunningNum;
    runningNum=$?
    if [ $runningNum -ne 0 ]; then
        for hbPath in ${hbPaths[@]}; do
            pid=`ps -ef | grep homebridge | grep $hbPath | grep -v grep | awk '{print $2}'`
            if [ -n "$pid" ]; then
                `kill $pid`
            fi
        done
    else
        echo "[WARN] YHHB is not runing.";
    fi
}

help() {
    getRunningNum;
    runningNum=$?
    echo $runningNum
}

printVersion() {
    echo "YHHB $version"
}

case "$1" in
    'start')
        start
        ;;
    'stop')
        stop
        ;;
    'restart')
        stop
        start
        ;;
    'status')
        status
        ;;
    'toggle')
        toggle
        ;;
    'help')
        help
        ;;
    'version')
        printVersion
        ;;
    *)
        exit 1
        ;;
esac

